#!/usr/bin/env python3
"""Generate a reviewable EchoAI generated.rs candidate from a release manifest."""
import argparse, json, re
from pathlib import Path

def rust_string(value: str) -> str: return json.dumps(value, ensure_ascii=False)
def const_name(resource_id: str) -> str: return re.sub(r"[^A-Z0-9]+", "_", resource_id.upper()).strip("_")
def main():
    p=argparse.ArgumentParser(); p.add_argument("--manifest",type=Path,required=True); p.add_argument("--output",type=Path,required=True); a=p.parse_args()
    data=json.loads(a.manifest.read_text(encoding="utf-8")); lines=["// @generated by EchoAIStore/scripts/resources/generate_rust.py; do not edit.", "", "#[derive(Debug, Clone, Copy)]", "pub struct GeneratedArchive {", "    pub id: &'static str,", "    pub owner: &'static str,", "    pub label_key: &'static str,", "    pub required: bool,", "    pub version: &'static str,", "    pub destination: &'static str,", "    pub url: &'static str,", "    pub sha256: &'static str,", "    pub key_files: &'static [&'static str],", "}", ""]
    for r in sorted(data["resources"],key=lambda x:x["id"]):
        ar=r["archive"]
        if not re.fullmatch(r"[0-9a-f]{64}",ar["sha256"]): raise ValueError(f"archive SHA-256 required for {r['id']}")
        lines += [f"pub const {const_name(r['id'])}: GeneratedArchive = GeneratedArchive {{", f"    id: {rust_string(r['id'])},", f"    owner: {rust_string(r['owner'])},", f"    label_key: {rust_string(r['label_key'])},", f"    required: {str(r['required']).lower()},", f"    version: {rust_string(r['version'])},", f"    destination: {rust_string(r['destination'])},", f"    url: {rust_string(ar['url'])},", f"    sha256: {rust_string(ar['sha256'])},", "    key_files: &[", *[f"        {rust_string(x)}," for x in r["key_files"]], "    ],", "};", ""]
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text("\n".join(lines),encoding="utf-8")
if __name__ == "__main__": main()
